name: Java CI with Ant

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
       distribution: 'adopt'
       java-version: '17'

    - name: Download Apache Ant
      run: |
       mkdir ant || exit 1
       cd ant || exit 1
       curl -O https://downloads.apache.org/ant/binaries/apache-ant-1.10.12-bin.tar.gz || exit 1
       tar -xf apache-ant-1.10.12-bin.tar.gz || exit 1
       export ANT_HOME=$(pwd)/apache-ant-1.10.12
       export PATH=$ANT_HOME/bin:$PATH
       continue-on-error: true
    

    - name: Build with Ant
      run: ant build

    - name: Run tests
      run: ant test
